services:
  # Cloud service
  cloud:
    stop_grace_period: 10s
    init: true
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 256M
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8002:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - SERVICE_NAME=cloud
      - CONTAINER_ENVIRONMENT=true
      - CLOUD_HOST_NAME=cloud
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
    command: bash -c "cd packages/cloud && bun run dev && bun run dev"
    networks:
      - augmentos-network-dev

  # Dashboard Manager service
  dashboard-manager:
    stop_grace_period: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: "no"
    ports:
      - "8012:80"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - SERVICE_NAME=dashboard-manager
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
      - ./logs:/app/logs
    command: bash -c "cd packages/apps/dashboard-manager && bun run dev"
    networks:
      - augmentos-network-dev
    # depends_on:
      # shared-packages:
      #   condition: service_healthy
      # cloud:
      #   condition: service_started

networks:
  augmentos-network-dev:
    driver: bridge
    external: true
    name: augmentos-network-dev

volumes:
  node_modules:
  bun_cache: